travis:
  secure:
    BINSTAR_TOKEN: PjTJHf14oAz7K1D3XKxdVVkt8vOyCtyYsZzX9FFqRIxf0YZgUfNLS+GYcQ6J0DkABPgp2ELUqbqofh9aAv8X1sy18m7HXZG4M9oaRX29V0sdJPC1gQtkTQ4nGrgTSbIWV+vnjjhceIZtscSR0Kl+vMld16Ad0QfM8tGPShvHISklpTpQl0a4abVfolEPUGrXO3JFQngmnfhWX5CHqN9vQBmMWOrQiu5EmylJRgJJDfPiHanfA0PrsZYKbuQTe9xzQZmgQez2q3eQ3riw2MSxcijLBRHbzSFxk81DaKECSCn1HnRNqO/bAs4kHOVDGt7BnNHOhCxSisPhBDfcIasOHd1R8JSPPLC0SZQz2JuO9AVD41WJmlgWsjGWzm8N+gbK4gUe9NVjUTIl+r6eJnDg+6+7TTaO9p4M5dqmXcyoteUgbKQ+IrzK2meIxk/hHXZl29HkW/xtbX1vBGrX0t8szQWcZFa8LDsAY3m+GUFNXT9Ky45IWtD7H7X7nG+XvW9LPMdY1ZPvP3UvbMKh2yeOSvqMnR5sy9HGTdIcSypzaiPFy8aLOSrgsnzW3jVIzLUs8GnIG2ADJDVmfl+QJl+ux0aDPmQ6USgOMuebDVHlbRda9+r/DcboxM/Vo8X6CEcGn9izF41y7MBydgrL/p+0ix9iyt6yt8TrJl+c1zvTu/M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
